#!/bin/bash

# Use the command 'quest show' to see all defaults and overrides
# task show [KEY-VALUE PAIR]

include dark-256.theme

# GENERAL SETTINGS *******************************************************************************

  editor=$EDITOR
  verbose=affected,blank,context,edit,footnote,label,new-id,news,project,special,sync,override,recur
  print.empty.columns=yes
  default.command=jobapps
  exit.on.missing.db=yes

# TABLE: JOB APPLICATIONS COLUMNS DEFINITION *****************************************************

  # col 1: uuid (built in)

  # col 2: job reference id ********************************
    uda.reference_id.label=reference
    uda.reference_id.type=string
    uda.reference_id.default=MISSING
    urgency.uda.reference_id.coefficient=0.5
    color.uda.reference_id=color242
    color.uda.reference_id.MISSING=white on red
  # end of col 2 ********************************************

  # col 3: role  ********************************
    # Role title will use the built-in description column
  # col 3: role  ********************************

  # col 4: employer  ********************************
    uda.employer.label=employer
    uda.employer.type=string
    urgency.uda.employer.coefficient=1.0
    color.uda.employer=color254
  # col 4: employer  ********************************

  # col 4: application date sent ********************************
    uda.date_sent.label=date sent
    uda.date_sent.type=date
    urgency.uda.date_sent.coefficient=3.0
    color.uda.date_sent=color252
  # col 4: application date sent  ********************************

  # col 5: response  ********************************
    uda.response.label=response
    uda.response.type=string
    uda.response.values=unsent,pending,interviewing,offered,rejected
    uda.response.default=unsent
    urgency.uda.response.coefficient=2.0
    color.uda.response=color251
  # col 5: response  ********************************

# resume **************************************
uda.resume.label=Resume UUID
uda.resume.type=string
urgency.uda.resume.coefficient=0.5
color.uda.resume=color250

# url **************************************
uda.url.label=Job URL
uda.url.type=string
uda.url.indicator=***
urgency.uda.url.coefficient=0.3
color.uda.url=color249
# uda.url.default=

# contact_name ************************************
uda.contact_name.label=Contact Name
uda.contact_name.type=string
urgency.uda.contact_name.coefficient=0.5
color.uda.contact_name=color248

# contact_email ***********************************
uda.contact_email.label=Contact Email
uda.contact_email.type=string
urgency.uda.contact_email.coefficient=0.5
color.uda.contact_email=color247

# contact_phone ***********************************
uda.contact_phone.label=Contact Phone
uda.contact_phone.type=string
urgency.uda.contact_phone.coefficient=0.3
color.uda.contact_phone=color246

# location ****************************************
uda.location.label=Location
uda.location.type=string
urgency.uda.location.coefficient=1.0
color.uda.location=color245

# salary_min **************************************
uda.salary.label=salary
uda.salary_min.type=numeric
urgency.uda.salary_min.coefficient=0.2
color.uda.salary_min=color244

# notes *******************************************
uda.notes.label=Notes
uda.notes.type=string
urgency.uda.notes.coefficient=0.0
color.uda.notes=color241

# priority *****************************************
urgency.uda.priority.C.coefficient=9.0   # CRITICAL
urgency.uda.priority.H.coefficient=6.0   # HIGH
urgency.uda.priority.M.coefficient=3.9   # MEDIUM
urgency.uda.priority.L.coefficient=1.8   # LOW
urgency.uda.priority.T.coefficient=-0.5  # TRIVIAL
color.uda.priority.C=color255 on color9
color.uda.priority.H=color250
color.uda.priority.M=color245
color.uda.priority.L=color242
color.uda.priority.T=color240
# priority *****************************************

# REPORTS *****************************************

  # Do $ task columns for details

  # SPECIFY:
    # 1. description
    # 2. columns
    # 3. labels
    # 4. filter
    # 5. sort
    # 6. grouping*

  # Job Applications Overview
    report.jobapps.description="Job Applications Overview"
    report.jobapps.columns=id,description.truncated,employer,date_sent,response,location,url.indicator,resume,reference_id
    # report.jobapps.labels= id, UUID,       status   employer, job title, app date,         location, URL,           resume
    report.jobapps.sort=date_sent+
    # report.jobapps.filter=status:pending
  # Job Applications Overview

  # url report
    report.url.description='show url'
    report.url.columns=id,uuid.short,job_title,description.truncated,url
  # url report

  # UUID REPORT
    report.uuid.description=""
    report.uuid.columns=id,uuid,description,status.short
    report.uuid.labels=id,uuid,description,st
    report.uuid.sort=id+
  # UUID REPORT

  # last inserted
    report.last_insert.description=Reports all info on last inserted task
    report.last_insert.columns=id,uuid.short,status,start.active,depends.indicator,priority,project.parent,tags,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description
    report.last_insert.labels=ID,UUID,Status,A,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
    report.last_insert.sort=entry-
    report.last_insert.filter=limit:1 status:pending
  # last inserted

# ALIASES ******************************************************************
  alias.insert=add # example

# TEMPLATES ******************************************************************

    # where X is uda name and V is value, F is foreground color and B is background color

    # uda.X.type=string|numeric|date|duration
    # uda.X.label=
    # uda.X.default=
    # uda.X.indicator=
    # uda.X.values=
    # 
    # color.uda.X=F on B
    # color.uda.X.V=F on B
    # color.uda.X.none=F on B
    # 
    # urgency.uda.X.coefficient=
    # urgency.uda.X.V.coefficient=

    # these are the complete configuration of a uda

# MISC *********************************************************************************
news.version=3.2.0
